### ISSUE TITLE
TBI - Secure storage is not being read when creating a service provider instance for an on-premise ABAP system

### ISSUE THREAD

**Issue by longieirl** [SAP/open-ux-tools#1089]
### Description (include screenshots)
Extend the `createAbapServiceProvider` method to support both credentials and service keys if found in the system secure store.

Existing functionality;
https://github.com/SAP/open-ux-tools/blob/main/packages/deploy-tooling/src/base/deploy.ts#L106

### Value
Provides a secure way to deploy to ABAP using service keys.
Provides an alternative to the user to deploy to an on-premise ABAP system. 

### Architecture Elaboration
No

### Notes
Found when testing on-premise ABAP deplyment where the secure store had the service keys for the target URL.

### Tasks
- [ ] Update `createAbapServiceProvider` to determine if the secure store also has service keys, if so, then generate a provider sinstance using these keys
- [ ] Update test cases

**Comment by tobiasqueck** [comment]
I don't think we should do that because `createAbapServiceProvider` is only called if the configuration defines that it is not a cloud system. If it is a cloud system then we execute `createAbapCloudServiceProvider` (which is also checking the store for credentials). 

What we could and should do instead, is to check in both functions if the returned system is of the incorrect type, and if yes, throw an exception informing the user that either the deployment configuration or the stored system information are wrong. We could even recommend how to fix it.

**Comment by tobiasqueck** [comment]
If I am not mistaken, then this one is also done, correct @cianmSAP @longieirl ?

**Comment by cianmSAP** [comment]
Yes, this is complete. Closing
