### ISSUE TITLE
BUG - ECONNRESET 

### ISSUE THREAD

**Issue by T1mey** [SAP/open-ux-tools#1225]
Hi,

we're using the latest version of @sap/ux-ui5-tooling 1.10.5.
When starting a deployment 

fiori deploy --failfast --yes --username ABAP_USER --password ABAP_PASSWORD --description "Desc" --noConfig --url https://system.corp.net/ --client 100 --transport ZZZK9B806P --package /CORP/XM10 --name /CORP/XM10_CHKL

```
info  transportRequestUploadCTS - 2023-08-28 14:04:34 info    abap-deploy-task: Creating archive from dist. 
info  transportRequestUploadCTS - 2023-08-28 14:04:34 info    abap-deploy-task: Archive created from dist. 
info  transportRequestUploadCTS - 2023-08-28 14:04:34 info    abap-deploy-task: Starting to deploy. 
info  transportRequestUploadCTS - 2023-08-28 14:04:35 info    abap-deploy-task: /CORP/XM10_CHKL found on target system: false 
**info  transportRequestUploadCTS - 2023-08-28 14:04:35 error   abap-deploy-task: read ECONNRESET**
```

we are getting a connection reset. After deletion of the application with se38 - /UI5/UI5_REPOSITORY_LOAD it is working.
If tha application is existing we are getting sometime that error. Not for all builds just for some ...

**Comment by longieirl** [comment]
Just to clarify, you are using the https://github.com/SAP/jenkins-library to manage deployment and getting "ECONNRESET" means the other side of the TCP conversation closed the connection for some reason.

Based on the log attached, the deployment task sent a POST request to deploy the app, since the GET call to `/Repositories('${encodeURIComponent(app)}')` returned false as a HTTP 404 was returned. So the initial GET request with your credentials is working as expected. If the app was found to be deployed it would send a PUT instead of a POST.

You can increase the logging by appending `--verbose` to your existing command but based on the exception thrown, its seems to be an issue with with established connection being terminated.

Are there any additional logs you can enable in `transportRequestUploadCTS` to see what is happening? Or to see the entire stack trace?

John

**Comment by T1mey** [comment]
> Just to clarify, you are using the https://github.com/SAP/jenkins-library to manage deployment and getting "ECONNRESET" which means the other side of the TCP conversation closed the connection for some reason.
> 
> Based on the log attached, the deployment task sent a POST request to deploy the app, since the GET call to `/Repositories('${encodeURIComponent(app)}')` returned false i.e. HTTP 404 was returned. So the initial GET request with your credentials is working as expected. If the app was found to be deployed it would send a PUT instead of a POST.
> 
> You can increase the logging by appending `--verbose` to your existing command but based on the exception thrown, its seems to be an issue with with established connection being terminated.
> 
> Are there any additional logs you can enable in `transportRequestUploadCTS` to see what is happening? Or to see the entire stack trace?
> 
> John

Hello John,

thanks for your reply. You're right we're using piper to run the step. 
As we're using a own docker image the tooling version was an older one.

ux-ui5-tooling-1.9.5

With the old one the deployment is working. Last days we updated the docker image to the new version 1.10.5 and it seems that the problems are coming with this. 

Any ideas?

**Comment by longieirl** [comment]
@T1mey the code being executed, based on your previous log, is executing a POST;
https://github.com/SAP/open-ux-tools/blob/main/packages/axios-extension/src/abap/ui5-abap-repository-service.ts#L339
However, in order to determine if the app is deployed or not, it first does a GET;
https://github.com/SAP/open-ux-tools/blob/main/packages/axios-extension/src/abap/ui5-abap-repository-service.ts#L149
which indicates the initial API call is successful and a 404 is returned. If any error other than a 404 is returend, then the exception would be shown in the logs.

Can you please re-run the command again with `--verbose` and append the config that is outputted, please obfuscate any sensitive data but keep the structure as is. 

Just to confirm, this is not blocking you as the deployment sometimes works? Correct?

**Comment by longieirl** [comment]
I've created a sample repo to replicate the docker image used in the piper CI/CD job;

https://github.com/longieirl/cloud-cf-helloworld-nodejs/tree/main

You can use these steps locally to validate if you can replicate the exception. It will also allow you to append the `--verbose` if see the config being used.

**Comment by tobiasqueck** [comment]
@T1mey are you still having the issue or should we close this one?

**Comment by longieirl** [comment]
Closing the issue as there is no response for over 8 months.
