### ISSUE TITLE
BUG -  fiori deploy tooling @sap/ux-ui5-tooling v1.11.5

### ISSUE THREAD

**Issue by T1mey** [SAP/open-ux-tools#1543]
Hello SAP,

we have a problem with the new tooling in version 1.11.5
We're uploading a SAPUI5 application with it and our bakend responds with a HTTP 415.

![image](https://github.com/SAP/open-ux-tools/assets/10464878/86c53913-a72b-4bd9-9deb-17fd0fc8880d)

With version 1.11.4 the request is accepted without any problem.

**Comment by tobiasqueck** [comment]
@longieirl @cianmSAP  could you please have a look if this is something in the `@sap-ux/deploy-tooling` or in `@sap/ux-ui5-tooling`?
`@sap/ux-ui5-tooling` v1.11.5 contains `@sap-ux/deploy-tooling` v0.11.7
`@sap/ux-ui5-tooling` v1.11.4 contained `@sap-ux/deploy-tooling` v0.11.4

**Comment by T1mey** [comment]
@longieirl 
Maybe an additional information. We can reproduce it when supplying a non existing transport request ID every time.

**Comment by T1mey** [comment]
@longieirl Any info ?

**Comment by longieirl** [comment]
@T1mey can you please try with the latest release of ui5-tooling v1.12.1 https://www.npmjs.com/package/@sap/ux-ui5-tooling
Thanks.
John

**Comment by ulr1chA** [comment]
Hi @longieirl,

issue is still the same:
![image](https://github.com/SAP/open-ux-tools/assets/141715584/f1c5dbc6-cc32-462e-8db6-6463b5beed81)

setup:
/data/tools/node/18.12.1/x64/lib
├── @sap/ux-ui5-tooling@1.12.2
├── @ui5/cli@3.9.0
├── @ui5/fs@3.0.5
├── @ui5/logger@3.0.0
├── corepack@0.14.2
└── npm@8.19.2

**Comment by T1mey** [comment]
We realized that the tooling is sending a HTTP header with "Accept Encoding" value "gzip,compress,deflate,br".
Seems that the **br** is causing trouble when the requests of the tooling are routed over SAP API Management.

https://docs.apigee.com/api-platform/troubleshoot/runtime/415-unsupported-media-type-unsupported-encoding

In former versions of the tooling the br was not present.

**Comment by longieirl** [comment]
@T1mey thanks for taking the time to debug through this issue. The issue has been resolved offline and here is the outcome;

1. Axios 1.2 introducing a change to support zlib and Brotli decompression https://github.com/axios/axios/blob/bf6974f16af6c72985f094a98d874c5a6adcdc83/lib/adapters/http.js#L38
2. [Fiori tools ](https://www.npmjs.com/package/@sap/ux-ui5-tooling) was recently bumped to use a later version of axios which introduced a newer version of axios
3. The 415 exception being returned is due to the `br` header in the default axios adapter being set https://github.com/axios/axios/blob/bf6974f16af6c72985f094a98d874c5a6adcdc83/lib/adapters/http.js#L400C36-L400C53

In this instance, the fix was the symptom is;
The backend sends the response in brotli encoding, and it is not understood by our API Management runtime. 

Fix is outlined at https://me.sap.com/notes/0003399769
