### ISSUE TITLE
FEATURE - Ability to import standard SAP Fiori app from ABAP Repository into VS Code like WebIDE can

### ISSUE THREAD

**Issue by mattieharding** [SAP/open-ux-tools#2028]
_As a Developer,
I want to view an SAP Developed ABAP UI5 deployed project in VS Code,
so that I understand how to adapt the project better_

### Description
Providing like-for-like features with WebIDE

**Comment by marianfoo** [comment]
Are there any APIs available for this request?
Which ones were used for WebIDE that can possibly be used again?

**Comment by tobiasqueck** [comment]
@mattieharding & @marianfoo there are APIs available to download the sources, however, we made the conscious decision not offer a feature to download deployed applications because we did not want to encourage the unsupported behavior of downloading an SAP delivered app, modifying it and deploying it under a different name.

@mattieharding when you say `adapt` are you talking about adaptation projects? If yes, could you give us some examples of where the app would be helpful for you?

**Comment by marianfoo** [comment]
@tobiasqueck totally understand and was expecting that, i just found [ui5-tools](https://github.com/CarlosOrozco88/ui5-tools) which is a VS Code Extension with the ability to download BSP Apps from an ABAP System.  
So i dont see a need to include the suggested feature into Fiori Tools

**Comment by mattieharding** [comment]
Great example. There was an sap Fiori app that created a mechanism to add columns to a list but required a special annotation on your custom columns that was only discoverable by looking deep in the controller file of the app...clearly was what you were meant to do but no documentation mentioned it anywhere! No Dev adaptation project was required at all once investigated.

**Comment by marianfoo** [comment]
We just had the same requirement too see what is going on in the standard app to decided how we can adapt it. Thats why i was searching for a solution too :)
Either use ui5-tools or  /UI5/UI5_REPOSITORY_LOAD (or even SE80) is a valid workaround. In my opinion that issue can be closed

**Comment by mattieharding** [comment]
I'm fine with that approach but most "SAP" Devs I deal with won't find it unless it is in the tool itself (sad but true)...

**Comment by tobiasqueck** [comment]
Thanks for your feedback, guys, as agreed, I am closing it.
